### ISSUE TITLE
Amazon Bedrock:  InvokeModel operation: The provided model doesn't support on-demand throughput - "meta.llama3-2-90b-instruct-v1:0"

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#411]
Filing below so if anyone else hits this there is a record which may help them.  The fix was to change how the model is specified in Bedrock.

I attempted to use llama 3.2 90b as per below from Amazon Bedrock, at the time I tried to use this the Bedrock docs showed I should call the model as `meta.llama3-2-90b-instruct-v1:0` yet it looks like I should have used `us.meta.llama3-2-90b-instruct-v1:0`.

Below is how I originally configured the model and where I hit an error:  

```
[models]
provider = "ChatBedrock"

[models.args]
model_id = "meta.llama3-2-90b-instruct-v1:0"
```

As I ran I saw this exception:

```

An error occurred (ValidationException) when calling the InvokeModel operation: The provided model doesn't support on-demand throughput.
WARNING:kai.service.kai_application.kai_application:Request to model failed for batch 1/1 for src/main/webapp/WEB-INF/beans.xml with exception An error occurred (ValidationException) when calling the InvokeModel operation: The provided model doesn't support on-demand throughput., retrying in 10.0s
An error occurred (ValidationException) when calling the InvokeModel operation: The provided model doesn't support on-demand throughput.
DEBUG:kai.service.kai_application.kai_application:Traceback (most recent call last):
  File "/Users/jmatthews/git/jwmatthews/kai/kai/service/kai_application/kai_application.py", line 181, in get_incident_solutions_for_file
    llm_result = self.model_provider.llm.invoke(prompt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 284, in invoke
    self.generate_prompt(
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 784, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 641, in generate
    raise e
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 631, in generate
    self._generate_with_cache(
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 853, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_aws/chat_models/bedrock.py", line 550, in _generate
    completion, tool_calls, llm_output = self._prepare_input_and_invoke(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_aws/llms/bedrock.py", line 795, in _prepare_input_and_invoke
    raise e
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/langchain_aws/llms/bedrock.py", line 781, in _prepare_input_and_invoke
    response = self.client.invoke_model(**request_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/botocore/client.py", line 1017, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The provided model doesn't support on-demand throughput.

```

Turns out to fix this I needed to make a small tweak to the configuration:

```
[models]
provider = "ChatBedrock"

[models.args]
model_id = "us.meta.llama3-2-90b-instruct-v1:0"
```

**Comment by jwmatthews** [comment]
This is not a bug, more I filed this just to help share awareness of how a model configuration issue can present in Bedrock

**Comment by fabianvf** [comment]
This should be added to our documentation
